insert into `account` (`email`, `password`, `type`) values ('hoaiphuc@ttdk.vn', 'OxTYPVug', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Hoài Phúc', 'Lạng Sơn', 'Hai Bà Trưng', '1991-07-05');
insert into `account` (`email`, `password`, `type`) values ('williamquan@ttdk.vn', 'eG2zmpu5', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm William Quân', 'Lạng Sơn', 'Hai Bà Trưng', '2009-11-14');
insert into `account` (`email`, `password`, `type`) values ('giavu@ttdk.vn', 'DomIqF2x', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Gia Vũ', 'Đồng Nai', 'Long Biên', '2009-05-13');
insert into `account` (`email`, `password`, `type`) values ('emilyvu@ttdk.vn', 'Zzmm5Lha', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Emily Vũ', 'Kiên Giang', 'Bắc Từ Liêm', '2011-12-23');
insert into `account` (`email`, `password`, `type`) values ('vodkatuan@ttdk.vn', 'zTyx61pC', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Vodka Tuấn', 'Tây Ninh', 'Hoàng Mai', '1994-01-05');
insert into `account` (`email`, `password`, `type`) values ('vodkavi@ttdk.vn', 'Z6Cuy1qQ', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Vodka Vi', 'Bắc Ninh', 'Tây Hồ', '1997-09-17');
insert into `account` (`email`, `password`, `type`) values ('quocduc@ttdk.vn', 'SONFJpov', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Quốc Đức', 'Trà Vinh', 'Thanh Xuân', '1993-08-11');
insert into `account` (`email`, `password`, `type`) values ('williamhoang@ttdk.vn', '8d0yKTWB', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm William Hoàng', 'Thừa Thiên Huế', 'Cầu Giấy', '1996-06-19');
insert into `account` (`email`, `password`, `type`) values ('emilyduc@ttdk.vn', 'nmteEcUN', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Emily Đức', 'Vĩnh Long', 'Sơn Trà', '2012-01-05');
insert into `account` (`email`, `password`, `type`) values ('hongvi@ttdk.vn', '6cAMS6xh', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Hồng Vi', 'Thừa Thiên Huế', 'Hoàng Mai', '2007-01-10');
insert into `account` (`email`, `password`, `type`) values ('elizabethsuy@ttdk.vn', 'kZzpDYa0', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Elizabeth Suy', 'Bà Rịa - Vũng Tàu', 'Hoàn Kiếm', '2001-07-13');
insert into `account` (`email`, `password`, `type`) values ('ducbinh@ttdk.vn', 'PZ8n4TeJ', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Đức Bình', 'Bến Tre', 'Nam Từ Liêm', '2000-12-19');
insert into `account` (`email`, `password`, `type`) values ('vodkalinh@ttdk.vn', 'GAOpMJsF', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Vodka Linh', 'Thái Bình', 'Ba Đình', '1993-06-04');
insert into `account` (`email`, `password`, `type`) values ('anphuc@ttdk.vn', 'D6XFyF1O', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm An Phúc', 'Khánh Hòa', 'Đống Đa', '1999-11-27');
insert into `account` (`email`, `password`, `type`) values ('hoaivi@ttdk.vn', 'Vb8nZG4s', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Hoài Vi', 'Thái Nguyên', 'Long Biên', '1990-02-23');
insert into `account` (`email`, `password`, `type`) values ('hongquan@ttdk.vn', 'N2YTr0iu', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Hồng Quân', 'Cà Mau', 'Thanh Khê', '1994-10-23');
insert into `account` (`email`, `password`, `type`) values ('ngochoang@ttdk.vn', 'zzDnD4xl', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Ngọc Hoàng', 'Tiền Giang', 'Long Biên', '2002-09-29');
insert into `account` (`email`, `password`, `type`) values ('duysuy@ttdk.vn', 'r5ERans7', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Duy Suy', 'Long An', 'Cầu Giấy', '2004-07-23');
insert into `account` (`email`, `password`, `type`) values ('johnyphuc@ttdk.vn', 'cS5xlem6', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Johny Phúc', 'Cần Thơ', 'Cầu Giấy', '1990-04-30');
insert into `account` (`email`, `password`, `type`) values ('jamestu@ttdk.vn', 'M6ljwL7V', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm James Tú', 'Bình Thuận', 'Bình Thạnh', '1990-11-06');
insert into `account` (`email`, `password`, `type`) values ('trungquang@ttdk.vn', 'ICjKPU7b', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Trung Quang', 'Lâm Đồng', 'Ba Đình', '1993-10-10');
insert into `account` (`email`, `password`, `type`) values ('thuylong@ttdk.vn', '4BSQg8cn', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Thuỳ Long', 'Trà Vinh', 'Đống Đa', '2009-07-02');
insert into `account` (`email`, `password`, `type`) values ('quocquan@ttdk.vn', 'epBre0nr', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Quốc Quân', 'Đà Nẵng', 'Long Biên', '2006-06-11');
insert into `account` (`email`, `password`, `type`) values ('williamlinh@ttdk.vn', 'uxBiH31n', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm William Linh', 'Yên Bái', 'Thanh Xuân', '2014-02-15');
insert into `account` (`email`, `password`, `type`) values ('hoaiquang@ttdk.vn', '0aQONI8P', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Hoài Quang', 'Bình Phước', 'Long Biên', '2008-04-28');
insert into `account` (`email`, `password`, `type`) values ('thanhlong@ttdk.vn', 'vT2ux4fr', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Thanh Long', 'Đồng Tháp', 'Hoàng Mai', '1994-09-05');
insert into `account` (`email`, `password`, `type`) values ('ducquan@ttdk.vn', 'q0ah57Tn', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Đức Quân', 'Vĩnh Long', 'Đống Đa', '2000-12-15');
insert into `account` (`email`, `password`, `type`) values ('baotu@ttdk.vn', '2Lti0i9J', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Bảo Tú', 'Yên Bái', 'Thanh Khê', '1993-08-11');
insert into `account` (`email`, `password`, `type`) values ('quocsuy@ttdk.vn', '5nly6Hcm', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Quốc Suy', 'Bạc Liêu', 'Đống Đa', '1996-08-25');
insert into `account` (`email`, `password`, `type`) values ('victoriavu@ttdk.vn', 'GwWN2NJf', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Victoria Vũ', 'Đồng Tháp', 'Hoàng Mai', '1997-10-12');
insert into `account` (`email`, `password`, `type`) values ('elizabethminh@ttdk.vn', '2gwZH8FG', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Elizabeth Minh', 'Hồ Chí Minh', 'Hà Đông', '1996-10-26');
insert into `account` (`email`, `password`, `type`) values ('vodkaphong@ttdk.vn', 'iWJX6G8X', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Vodka Phong', 'Thừa Thiên Huế', 'Bắc Từ Liêm', '1994-08-27');
insert into `account` (`email`, `password`, `type`) values ('emilylinh@ttdk.vn', 'HQ2R09lr', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Emily Linh', 'Đồng Tháp', 'Hoàng Mai', '1999-10-04');
insert into `account` (`email`, `password`, `type`) values ('victoriaquan@ttdk.vn', 'bLnWz9ck', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Victoria Quân', 'Hải Dương', 'Ba Đình', '2001-07-19');
insert into `account` (`email`, `password`, `type`) values ('hoaiminh@ttdk.vn', '43UsbI0g', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Hoài Minh', 'Hải Phòng', 'Ba Đình', '2003-02-23');
insert into `account` (`email`, `password`, `type`) values ('baolinh@ttdk.vn', 'uRJ89S0I', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Bảo Linh', 'Cần Thơ', 'Ba Đình', '1995-01-28');
insert into `account` (`email`, `password`, `type`) values ('anvu@ttdk.vn', 'hYXeQ5px', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm An Vũ', 'Phú Thọ', 'Bình Thạnh', '1997-04-18');
insert into `account` (`email`, `password`, `type`) values ('vladimirphong@ttdk.vn', 'o4r7Syc1', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Vladimir Phong', 'Bình Dương', 'Bắc Từ Liêm', '2014-12-09');
insert into `account` (`email`, `password`, `type`) values ('giaduc@ttdk.vn', 'mEdr1VBL', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Gia Đức', 'Bà Rịa - Vũng Tàu', 'Thanh Xuân', '2004-10-27');
insert into `account` (`email`, `password`, `type`) values ('huuvi@ttdk.vn', 'hMy81GiA', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Hữu Vi', 'Lào Cai', 'Thanh Xuân', '2009-04-02');
insert into `account` (`email`, `password`, `type`) values ('johnytu@ttdk.vn', 'UmtPbH3n', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Johny Tú', 'Hà Nam', 'Hai Bà Trưng', '2005-09-13');
insert into `account` (`email`, `password`, `type`) values ('quocsuy@ttdk.vn', 'HE80SIs6', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Quốc Suy', 'Lào Cai', 'Hoàn Kiếm', '2014-01-10');
insert into `account` (`email`, `password`, `type`) values ('viktorminh@ttdk.vn', 'GvLcqubf', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Viktor Minh', 'Đắk Nông', 'Hải Châu', '2002-11-19');
insert into `account` (`email`, `password`, `type`) values ('thuynam@ttdk.vn', 'SDe53Ntj', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Thuỳ Nam', 'Quảng Ninh', 'Hai Bà Trưng', '2004-03-10');
insert into `account` (`email`, `password`, `type`) values ('victoriatu@ttdk.vn', 's3P1X8S1', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Victoria Tú', 'Gia Lai', 'Ba Đình', '2002-10-28');
insert into `account` (`email`, `password`, `type`) values ('giaphong@ttdk.vn', 'wIoCSFre', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Gia Phong', 'Vĩnh Phúc', 'Hai Bà Trưng', '1998-10-12');
insert into `account` (`email`, `password`, `type`) values ('thuyhoang@ttdk.vn', 'm87PORz3', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Thuỳ Hoàng', 'Yên Bái', 'Long Biên', '2012-07-24');
insert into `account` (`email`, `password`, `type`) values ('jamesthang@ttdk.vn', 'CicpOG5N', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm James Thắng', 'Hưng Yên', 'Ba Đình', '1992-06-08');
insert into `account` (`email`, `password`, `type`) values ('ngocbinh@ttdk.vn', 'bFNmTyfZ', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Ngọc Bình', 'Bắc Ninh', 'Tây Hồ', '2005-09-09');
insert into `account` (`email`, `password`, `type`) values ('vladimirbinh@ttdk.vn', 'XeO7tiF6', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Vladimir Bình', 'Quảng Nam', 'Hoàn Kiếm', '1996-12-25');
insert into `account` (`email`, `password`, `type`) values ('honeysuy@ttdk.vn', '8nAed9rV', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Honey Suy', 'Lạng Sơn', 'Bắc Từ Liêm', '2001-04-22');
insert into `account` (`email`, `password`, `type`) values ('ductu@ttdk.vn', 'CNuZwrAI', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Đức Tú', 'Đồng Nai', 'Hoàng Mai', '1991-11-30');
insert into `account` (`email`, `password`, `type`) values ('vodkanam@ttdk.vn', 'mgX5zwfw', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Vodka Nam', 'Sóc Trăng', 'Đống Đa', '2004-09-10');
insert into `account` (`email`, `password`, `type`) values ('davidphuc@ttdk.vn', 'Ak03jJTW', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm David Phúc', 'Ninh Thuận', 'Sơn Trà', '2001-10-14');
insert into `account` (`email`, `password`, `type`) values ('quocquang@ttdk.vn', 'G1xHLLTZ', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Quốc Quang', 'Lâm Đồng', 'Nam Từ Liêm', '1998-03-08');
insert into `account` (`email`, `password`, `type`) values ('quoctuan@ttdk.vn', 'dHnEdRj9', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Quốc Tuấn', 'Hưng Yên', 'Hải Châu', '1994-06-19');
insert into `account` (`email`, `password`, `type`) values ('honeyphong@ttdk.vn', 'ClMA0ZWF', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Honey Phong', 'Ninh Thuận', 'Hai Bà Trưng', '1990-12-13');
insert into `account` (`email`, `password`, `type`) values ('hongminh@ttdk.vn', 'DtYgYsLn', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Hồng Minh', 'Đồng Tháp', 'Bắc Từ Liêm', '2001-07-17');
insert into `account` (`email`, `password`, `type`) values ('thuyphong@ttdk.vn', '7CKRNsx9', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Thuỳ Phong', 'Ninh Bình', 'Hà Đông', '2009-11-30');
insert into `account` (`email`, `password`, `type`) values ('michaelan@ttdk.vn', '8VqtZWHn', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Michael Ân', 'Bình Định', 'Hà Đông', '2005-06-13');
insert into `account` (`email`, `password`, `type`) values ('quocphuc@ttdk.vn', 'OghS3JQi', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Quốc Phúc', 'Quảng Ninh', 'Cầu Giấy', '1997-11-14');
insert into `account` (`email`, `password`, `type`) values ('thiphuc@ttdk.vn', '924dfj4C', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Thị Phúc', 'Vĩnh Phúc', 'Bình Thạnh', '2008-08-02');
insert into `account` (`email`, `password`, `type`) values ('baotu@ttdk.vn', 'FdPVSUWE', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Bảo Tú', 'Bình Thuận', 'Thanh Khê', '1999-12-27');
insert into `account` (`email`, `password`, `type`) values ('thiquan@ttdk.vn', 'VDXUy2Lv', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Thị Quân', 'Hà Nam', 'Thanh Xuân', '2007-12-19');
insert into `account` (`email`, `password`, `type`) values ('thuyquan@ttdk.vn', 'P2m1tUGt', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Thuỳ Quân', 'Quảng Ngãi', 'Bình Thạnh', '1996-01-06');
insert into `account` (`email`, `password`, `type`) values ('thanhtu@ttdk.vn', 'K6bCGvRR', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Thanh Tú', 'Tiền Giang', 'Đống Đa', '2012-04-05');
insert into `account` (`email`, `password`, `type`) values ('elizabethan@ttdk.vn', 'bk7B8PfC', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Elizabeth Ân', 'Điện Biên', 'Sơn Trà', '2014-09-11');
insert into `account` (`email`, `password`, `type`) values ('duynam@ttdk.vn', '2bzHVAjI', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Duy Nam', 'Nam Định', 'Long Biên', '2014-03-14');
insert into `account` (`email`, `password`, `type`) values ('huuphong@ttdk.vn', 'H1qdsda3', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Hữu Phong', 'Thái Bình', 'Bình Thạnh', '2013-05-09');
insert into `account` (`email`, `password`, `type`) values ('duylong@ttdk.vn', 'QjH8y4gl', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Duy Long', 'Sóc Trăng', 'Ba Đình', '2002-09-24');
insert into `account` (`email`, `password`, `type`) values ('trungquang@ttdk.vn', 'EfPFOoMq', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Trung Quang', 'Bến Tre', 'Sơn Trà', '2011-03-02');
insert into `account` (`email`, `password`, `type`) values ('vanminh@ttdk.vn', 'RbfcYPoM', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Văn Minh', 'Điện Biên', 'Bắc Từ Liêm', '1990-07-04');
insert into `account` (`email`, `password`, `type`) values ('michaelnam@ttdk.vn', '76CQesqZ', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Michael Nam', 'Ninh Bình', 'Ba Đình', '1999-03-07');
insert into `account` (`email`, `password`, `type`) values ('thanhphuc@ttdk.vn', 'x4nSE0AW', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Thanh Phúc', 'Bắc Ninh', 'Bắc Từ Liêm', '2005-06-02');
insert into `account` (`email`, `password`, `type`) values ('thinhvi@ttdk.vn', 'zSwRJcGu', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Thịnh Vi', 'Thái Bình', 'Long Biên', '2009-06-26');
insert into `account` (`email`, `password`, `type`) values ('ducminh@ttdk.vn', 'DaH52N0G', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Đức Minh', 'Lạng Sơn', 'Hải Châu', '1996-10-28');
insert into `account` (`email`, `password`, `type`) values ('honglinh@ttdk.vn', 'En94teWX', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Hồng Linh', 'Thanh Hóa', 'Long Biên', '1998-12-13');
insert into `account` (`email`, `password`, `type`) values ('vanbinh@ttdk.vn', 'jfTwONIl', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Văn Bình', 'Bình Phước', 'Cầu Giấy', '1990-07-14');
insert into `account` (`email`, `password`, `type`) values ('honeytu@ttdk.vn', 'fYoyS3y2', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Honey Tú', 'Cà Mau', 'Tây Hồ', '1996-09-21');
insert into `account` (`email`, `password`, `type`) values ('alexphong@ttdk.vn', 'Xcj10P6I', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Alex Phong', 'Bình Định', 'Long Biên', '2005-08-23');
insert into `account` (`email`, `password`, `type`) values ('michaelvi@ttdk.vn', 'UBH0Mikp', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Michael Vi', 'Bình Dương', 'Long Biên', '2001-12-31');
insert into `account` (`email`, `password`, `type`) values ('quocphuc@ttdk.vn', 'RuNVEsRh', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Quốc Phúc', 'Bạc Liêu', 'Tây Hồ', '2009-09-26');
insert into `account` (`email`, `password`, `type`) values ('johnynam@ttdk.vn', '5cHUAull', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Johny Nam', 'Thanh Hóa', 'Hoàng Mai', '2004-02-17');
insert into `account` (`email`, `password`, `type`) values ('huusuy@ttdk.vn', 'llvxHhPL', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Hữu Suy', 'Trà Vinh', 'Ba Đình', '1995-08-16');
insert into `account` (`email`, `password`, `type`) values ('victoriatu@ttdk.vn', 'tM9kZzWj', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Victoria Tú', 'Kon Tum', 'Sơn Trà', '1990-10-05');
insert into `account` (`email`, `password`, `type`) values ('williamtuan@ttdk.vn', 'QQ2zffRe', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm William Tuấn', 'Sóc Trăng', 'Ba Đình', '1993-09-20');
insert into `account` (`email`, `password`, `type`) values ('viktortu@ttdk.vn', 'iG1gPHJl', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Viktor Tú', 'Thừa Thiên Huế', 'Cầu Giấy', '2013-01-05');
insert into `account` (`email`, `password`, `type`) values ('baolinh@ttdk.vn', 'dxLG0AJR', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Bảo Linh', 'Gia Lai', 'Hoàn Kiếm', '1999-06-19');
insert into `account` (`email`, `password`, `type`) values ('viktorthang@ttdk.vn', 'R9ve7wqb', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Viktor Thắng', 'Phú Thọ', 'Long Biên', '1992-11-01');
insert into `account` (`email`, `password`, `type`) values ('ductuan@ttdk.vn', '26E4ep07', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Đức Tuấn', 'Gia Lai', 'Long Biên', '1992-10-01');
insert into `account` (`email`, `password`, `type`) values ('johnylong@ttdk.vn', 'AJEow4vn', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Johny Long', 'Quảng Bình', 'Bắc Từ Liêm', '1994-08-24');
insert into `account` (`email`, `password`, `type`) values ('baoduc@ttdk.vn', '0XpJNOye', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Bảo Đức', 'An Giang', 'Ba Đình', '2007-08-16');
insert into `account` (`email`, `password`, `type`) values ('huunam@ttdk.vn', 'n1JmW84J', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Hữu Nam', 'Bạc Liêu', 'Thanh Khê', '1990-07-12');
insert into `account` (`email`, `password`, `type`) values ('thuylinh@ttdk.vn', 'FYvIQdFk', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Thuỳ Linh', 'Vĩnh Phúc', 'Tây Hồ', '1994-08-13');
insert into `account` (`email`, `password`, `type`) values ('ngocphong@ttdk.vn', 'vwTofdME', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Ngọc Phong', 'Bạc Liêu', 'Long Biên', '2006-03-14');
insert into `account` (`email`, `password`, `type`) values ('jamesphong@ttdk.vn', 'vk57zSZm', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm James Phong', 'Lạng Sơn', 'Hai Bà Trưng', '2002-05-09');
insert into `account` (`email`, `password`, `type`) values ('huunam@ttdk.vn', 'VqL9rVNu', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Hữu Nam', 'Tây Ninh', 'Hai Bà Trưng', '2006-09-22');
insert into `account` (`email`, `password`, `type`) values ('victoriatuan@ttdk.vn', 'mmhTeFr0', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Victoria Tuấn', 'Thái Nguyên', 'Ba Đình', '1998-01-14');
insert into `account` (`email`, `password`, `type`) values ('ductu@ttdk.vn', 'GX2IWwIz', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Đức Tú', 'Quảng Trị', 'Cầu Giấy', '1995-10-26');
insert into `account` (`email`, `password`, `type`) values ('viktorquang@ttdk.vn', 'lHbYrDDf', '0');
insert into `centre` (`id`, `name`,`city`,`district`,`activation`) values ((SELECT MAX(ID) FROM `account`), 'Trung tâm Đăng kiểm Viktor Quang', 'An Giang', 'Long Biên', '1999-12-16');